"""odrkit.content — verbatim legal disclaimer + synthetic-data notice.

The disclaimer text lives in ``disclaimer.txt`` next to this file and MUST be
rendered into every artifact byte-for-byte — never edited, paraphrased, or
regenerated by an LLM. This module only loads and lightly paragraphs it.
"""

from __future__ import annotations

from pathlib import Path

_CONTENT_DIR = Path(__file__).resolve().parent
_DISCLAIMER_PATH = _CONTENT_DIR / "disclaimer.txt"

COPYRIGHT_LINE = "© Ops Data Reporter. Internal use only."
PROVENANCE_LINE = (
    "Generated by odrkit (deterministic engine) — no figure in this report "
    "was computed or altered by a language model."
)

SYNTHETIC_NOTICE = (
    "ILLUSTRATIVE SYNTHETIC DATA — not real ODR figures. Every value in this "
    "artifact is computed from a seeded synthetic dataset for demonstration "
    "purposes only."
)


def disclaimer_text() -> str:
    """Return the verbatim disclaimer text, unmodified."""
    return _DISCLAIMER_PATH.read_text(encoding="utf-8")


def disclaimer_paragraphs() -> list[str]:
    """Return the verbatim disclaimer split into paragraphs (blank-line delimited).

    Splitting on blank lines is presentation only — no paragraph's text is
    edited, reordered, or summarized.
    """
    text = disclaimer_text()
    return [p.strip() for p in text.split("\n\n") if p.strip()]


def synthetic_notice() -> str:
    """Return the loud synthetic-data marker string for artifact footers."""
    return SYNTHETIC_NOTICE
